

development:
  adapter: postgresql
  encoding: unicode
  database: spork_db
  pool: 5
  username: blakerego
  password: blakerego


test:
  adapter: postgresql
  encoding: unicode
  database: spork_db_test
  pool: 5
  username: blakerego
  password: blakerego

production:
  adapter: postgresql
  encoding: unicode
  database: spork_db
  pool: 5
  username: brego
  password: 

